version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\wenchangshou2\zui

environment:
  GOPATH: c:\gopath
  GO111MODULE: on

install:
  - choco install mingw
  - SET PATH=C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;%PATH%
  - set PATH=%GOROOT%\bin;%GOPATH%\bin;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin;%PATH%
  - set PATH_WAS=%PATH%
  - set CGO_ENABLED=1
  - go version
  - go env

build_script:
  - go build
  - 7z a myapp.zip zui.exe*
  - ls .
artifacts:
  - path: myapp.zip
    name: zui