version: "{build}"

os: Windows Server 2019	

clone_folder: c:\gopath\src\github.com\wenchangshou2\zui

environment:
  GOPATH: c:\gopath
  GO111MODULE: on

install:
  - set pATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build_script:
  - go build