version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\wenchangshou2\zui

environment:
  GOPATH: c:\gopath
  GO111MODULE: on

install:
  - set PATH=%GOPATH%\bin;C:\cygwin64\bin;c:\go\bin;%PATH%
  - go version
  - go env

build_script:
  - go build