version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\wenchangshou2\zui

environment:
  GOPATH: c:\gopath
  GO111MODULE: on

install:
  - set PATH=%GOPATH%\bin;c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\bin;c:\go\bin;%PATH%
  - go version
  - go env

build_script:
  - go build